toc:
  - section_code: '010000'
    section_name: 'I. 회사의 개요'
    children:
      - section_code: '010100'
        section_name: '1. 회사의 개요'
        children: []
      - section_code: '010200'
        section_name: '2. 회사의 연혁'
        children: []
      - section_code: '010300'
        section_name: '3. 자본금 변동사항'
        children: []
      - section_code: '010400'
        section_name: '4. 주식의 총수 등'
        children: []
      - section_code: '010500'
        section_name: '5. 정관에 관한 사항'
        children: []
  - section_code: '020000'
    section_name: 'II. 사업의 내용'
    children:
      - section_code: '020100'
        section_name: '1. 사업의 개요'
        children: []
      - section_code: '020200'
        section_name: '2. 주요 제품 및 서비스'
        children: []
      - section_code: '020300'
        section_name: '3. 원재료 및 생산설비'
        children: []
      - section_code: '020400'
        section_name: '4. 매출 및 수주상황'
        children: []
      - section_code: '020500'
        section_name: '5. 위험관리 및 파생거래'
        children: []
      - section_code: '020600'
        section_name: '6. 주요계약 및 연구개발활동'
        children: []
      - section_code: '020700'
        section_name: '7. 기타 참고사항'
        children: []
  - section_code: '030000'
    section_name: 'III. 재무에 관한 사항'
    children:
      - section_code: '030100'
        section_name: '1. 요약재무정보'
        children: []
      - section_code: '030200'
        section_name: '2. 연결재무제표'
        children:
          - section_code: '030201'
            section_name: '2-1. 연결 재무상태표'
            children: []
          - section_code: '030202'
            section_name: '2-2. 연결 손익계산서'
            children: []
          - section_code: '030203'
            section_name: '2-3. 연결 포괄손익계산서'
            children: []
          - section_code: '030204'
            section_name: '2-4. 연결 자본변동표'
            children: []
          - section_code: '030205'
            section_name: '2-5. 연결 현금흐름표'
            children: []
      - section_code: '030300'
        section_name: '3. 연결재무제표 주석'
        children:
          - section_code: '030301'
            section_name: '1. 일반적 사항 (연결)'
            children: []
          - section_code: '030302'
            section_name: '2. 중요한 회계처리방침 (연결)'
            children: []
          - section_code: '030303'
            section_name: '3. 중요한 회계추정 및 가정 (연결)'
            children: []
          - section_code: '030304'
            section_name: '4. 범주별 금융상품 (연결)'
            children: []
          - section_code: '030305'
            section_name: '5. 금융자산의 양도 (연결)'
            children: []
          - section_code: '030306'
            section_name: '6. 공정가치금융자산 (연결)'
            children: []
          - section_code: '030307'
            section_name: '7. 매출채권 및 미수금 (연결)'
            children: []
          - section_code: '030308'
            section_name: '8. 재고자산 (연결)'
            children: []
          - section_code: '030309'
            section_name: '9. 관계기업 및 공동기업 투자 (연결)'
            children: []
          - section_code: '030310'
            section_name: '10. 유형자산 (연결)'
            children: []
          - section_code: '030311'
            section_name: '11. 무형자산 (연결)'
            children: []
          - section_code: '030312'
            section_name: '12. 차입금 (연결)'
            children: []
          - section_code: '030313'
            section_name: '13. 사채 (연결)'
            children: []
          - section_code: '030314'
            section_name: '14. 순확정급여부채(자산) (연결)'
            children: []
          - section_code: '030315'
            section_name: '15. 충당부채 (연결)'
            children: []
          - section_code: '030316'
            section_name: '16. 우발부채와 약정사항 (연결)'
            children: []
          - section_code: '030317'
            section_name: '17. 계약부채 (연결)'
            children: []
          - section_code: '030318'
            section_name: '18. 자본금 (연결)'
            children: []
          - section_code: '030319'
            section_name: '19. 연결이익잉여금 (연결)'
            children: []
          - section_code: '030320'
            section_name: '20. 기타자본항목 (연결)'
            children: []
          - section_code: '030321'
            section_name: '21. 비용의 성격별 분류 (연결)'
            children: []
          - section_code: '030322'
            section_name: '22. 판매비와관리비 (연결)'
            children: []
          - section_code: '030323'
            section_name: '23. 기타수익 및 기타비용 (연결)'
            children: []
          - section_code: '030324'
            section_name: '24. 금융수익 및 금융비용 (연결)'
            children: []
          - section_code: '030325'
            section_name: '25. 법인세비용 (연결)'
            children: []
          - section_code: '030326'
            section_name: '26. 주당이익 (연결)'
            children: []
          - section_code: '030327'
            section_name: '27. 현금흐름표 (연결)'
            children: []
          - section_code: '030328'
            section_name: '28. 재무위험관리 (연결)'
            children: []
          - section_code: '030329'
            section_name: '29. 부문별 보고 (연결)'
            children: []
          - section_code: '030330'
            section_name: '30. 특수관계자와의 거래 (연결)'
            children: []
          - section_code: '030331'
            section_name: '31. 비지배지분 (연결)'
            children: []
          - section_code: '030332'
            section_name: '32. 매각예정분류(처분자산집단) (연결)'
            children: []
          - section_code: '030333'
            section_name: '33. 보고기간 후 사건 (연결)'
            children: []
      - section_code: '030400'
        section_name: '4. 재무제표'
        children:
          - section_code: '030401'
            section_name: '4-1. 재무상태표'
            children: []
          - section_code: '030402'
            section_name: '4-2. 손익계산서'
            children: []
          - section_code: '030403'
            section_name: '4-3. 포괄손익계산서'
            children: []
          - section_code: '030404'
            section_name: '4-4. 자본변동표'
            children: []
          - section_code: '030405'
            section_name: '4-5. 현금흐름표'
            children: []
      - section_code: '030500'
        section_name: '5. 재무제표 주석'
        children:
          - section_code: '030501'
            section_name: '1. 일반적 사항'
            children: []
          - section_code: '030502'
            section_name: '2. 중요한 회계처리방침'
            children: []
          - section_code: '030503'
            section_name: '3. 중요한 회계추정 및 가정'
            children: []
          - section_code: '030504'
            section_name: '4. 범주별 금융상품'
            children: []
          - section_code: '030505'
            section_name: '5. 금융자산의 양도'
            children: []
          - section_code: '030506'
            section_name: '6. 공정가치금융자산'
            children: []
          - section_code: '030507'
            section_name: '7. 매출채권 및 미수금'
            children: []
          - section_code: '030508'
            section_name: '8. 재고자산'
            children: []
          - section_code: '030509'
            section_name: '9. 종속기업, 관계기업 및 공동기업 투자'
            children: []
          - section_code: '030510'
            section_name: '10. 유형자산'
            children: []
          - section_code: '030511'
            section_name: '11. 무형자산'
            children: []
          - section_code: '030512'
            section_name: '12. 차입금'
            children: []
          - section_code: '030513'
            section_name: '13. 사채'
            children: []
          - section_code: '030514'
            section_name: '14. 순확정급여부채(자산)'
            children: []
          - section_code: '030515'
            section_name: '15. 충당부채'
            children: []
          - section_code: '030516'
            section_name: '16. 우발부채와 약정사항'
            children: []
          - section_code: '030517'
            section_name: '17. 계약부채'
            children: []
          - section_code: '030518'
            section_name: '18. 자본금'
            children: []
          - section_code: '030519'
            section_name: '19. 이익잉여금'
            children: []
          - section_code: '030520'
            section_name: '20. 기타자본항목'
            children: []
          - section_code: '030521'
            section_name: '21. 비용의 성격별 분류'
            children: []
          - section_code: '030522'
            section_name: '22. 판매비와관리비'
            children: []
          - section_code: '030523'
            section_name: '23. 기타수익 및 기타비용'
            children: []
          - section_code: '030524'
            section_name: '24. 금융수익 및 금융비용'
            children: []
          - section_code: '030525'
            section_name: '25. 법인세비용'
            children: []
          - section_code: '030526'
            section_name: '26. 주당이익'
            children: []
          - section_code: '030527'
            section_name: '27. 현금흐름표'
            children: []
          - section_code: '030528'
            section_name: '28. 재무위험관리'
            children: []
          - section_code: '030529'
            section_name: '29. 부문별 보고'
            children: []
          - section_code: '030530'
            section_name: '30. 특수관계자와의 거래'
            children: []
          - section_code: '030531'
            section_name: '31. 보고기간 후 사건'
            children: []
      - section_code: '030600'
        section_name: '6. 배당에 관한 사항'
        children: []
      - section_code: '030700'
        section_name: '7. 증권의 발행을 통한 자금조달에 관한 사항'
        children:
          - section_code: '030701'
            section_name: '7-1. 증권의 발행을 통한 자금조달 실적'
            children: []
          - section_code: '030702'
            section_name: '7-2. 증권의 발행을 통해 조달된 자금의 사용실적'
            children: []
      - section_code: '030800'
        section_name: '8. 기타 재무에 관한 사항'
        children: []
  - section_code: '040000'
    section_name: 'IV. 이사의 경영진단 및 분석의견'
    children: []
  - section_code: '050000'
    section_name: 'V. 회계감사인의 감사의견 등'
    children:
      - section_code: '050100'
        section_name: '1. 외부감사에 관한 사항'
        children: []
      - section_code: '050200'
        section_name: '2. 내부통제에 관한 사항'
        children: []
  - section_code: '060000'
    section_name: 'VI. 이사회 등 회사의 기관에 관한 사항'
    children:
      - section_code: '060100'
        section_name: '1. 이사회에 관한 사항'
        children: []
      - section_code: '060200'
        section_name: '2. 감사제도에 관한 사항'
        children: []
      - section_code: '060300'
        section_name: '3. 주주총회 등에 관한 사항'
        children: []
  - section_code: '070000'
    section_name: 'VII. 주주에 관한 사항'
    children: []
  - section_code: '080000'
    section_name: 'VIII. 임원 및 직원 등에 관한 사항'
    children:
      - section_code: '080100'
        section_name: '1. 임원 및 직원 등의 현황'
        children: []
      - section_code: '080200'
        section_name: '2. 임원의 보수 등'
        children: []
  - section_code: '090000'
    section_name: 'IX. 계열회사 등에 관한 사항'
    children: []
  - section_code: '100000'
    section_name: 'X. 대주주 등과의 거래내용'
    children: []
  - section_code: '110000'
    section_name: 'XI. 그 밖에 투자자 보호를 위하여 필요한 사항'
    children:
      - section_code: '110100'
        section_name: '1. 공시내용 진행 및 변경사항'
        children: []
      - section_code: '110200'
        section_name: '2. 우발부채 등에 관한 사항'
        children: []
      - section_code: '110300'
        section_name: '3. 제재 등과 관련된 사항'
        children: []
      - section_code: '110400'
        section_name: '4. 작성기준일 이후 발생한 주요사항 등 기타사항'
        children: []
  - section_code: '120000'
    section_name: 'XII. 상세표'
    children:
      - section_code: '120100'
        section_name: '1. 연결대상 종속회사 현황(상세)'
        children: []
      - section_code: '120200'
        section_name: '2. 계열회사 현황(상세)'
        children: []
      - section_code: '120300'
        section_name: '3. 타법인출자 현황(상세)'
        children: []
      - section_code: '120400'
        section_name: '4. 연구개발실적(상세)'
        children: []
