toc:
  - section_code: '0100'
    section_name: 'I. 회사의 개요'
    children:
      - section_code: '0101'
        section_name: '1. 회사의 개요'
      - section_code: '0102'
        section_name: '2. 회사의 연혁'
      - section_code: '0103'
        section_name: '3. 자본금 변동사항'
      - section_code: '0104'
        section_name: '4. 주식의 총수 등'
      - section_code: '0105'
        section_name: '5. 정관에 관한 사항'
  - section_code: '0200'
    section_name: 'II. 사업의 내용'
    children:
      - section_code: '0201'
        section_name: '1. 사업의 개요'
      - section_code: '0202'
        section_name: '2. 주요 제품 및 서비스'
      - section_code: '0203'
        section_name: '3. 원재료 및 생산설비'
      - section_code: '0204'
        section_name: '4. 매출 및 수주상황'
      - section_code: '0205'
        section_name: '5. 위험관리 및 파생거래'
      - section_code: '0206'
        section_name: '6. 주요계약 및 연구개발활동'
      - section_code: '0207'
        section_name: '7. 기타 참고사항'
  - section_code: '0300'
    section_name: 'III. 재무에 관한 사항'
    children:
      - section_code: '0301'
        section_name: '1. 요약재무정보'
      - section_code: '0302'
        section_name: '2. 연결재무제표'
        children:
          - section_code: '0303'
            section_name: '2-1. 연결 재무상태표'
          - section_code: '0304'
            section_name: '2-2. 연결 손익계산서'
          - section_code: '0305'
            section_name: '2-3. 연결 포괄손익계산서'
          - section_code: '0306'
            section_name: '2-4. 연결 자본변동표'
          - section_code: '0307'
            section_name: '2-5. 연결 현금흐름표'
      - section_code: '0308'
        section_name: '3. 연결재무제표 주석'
        children:
          - section_code: '0309'
            section_name: '1. 일반적 사항 (연결)'
          - section_code: '0310'
            section_name: '2. 중요한 회계처리방침 (연결)'
          - section_code: '0311'
            section_name: '3. 중요한 회계추정 및 가정 (연결)'
          - section_code: '0312'
            section_name: '4. 범주별 금융상품 (연결)'
          - section_code: '0313'
            section_name: '5. 금융자산의 양도 (연결)'
          - section_code: '0314'
            section_name: '6. 공정가치금융자산 (연결)'
          - section_code: '0315'
            section_name: '7. 매출채권 및 미수금 (연결)'
          - section_code: '0316'
            section_name: '8. 재고자산 (연결)'
          - section_code: '0317'
            section_name: '9. 관계기업 및 공동기업 투자 (연결)'
          - section_code: '0318'
            section_name: '10. 유형자산 (연결)'
          - section_code: '0319'
            section_name: '11. 무형자산 (연결)'
          - section_code: '0320'
            section_name: '12. 차입금 (연결)'
          - section_code: '0321'
            section_name: '13. 사채 (연결)'
          - section_code: '0322'
            section_name: '14. 순확정급여부채(자산) (연결)'
          - section_code: '0323'
            section_name: '15. 충당부채 (연결)'
          - section_code: '0324'
            section_name: '16. 우발부채와 약정사항 (연결)'
          - section_code: '0325'
            section_name: '17. 계약부채 (연결)'
          - section_code: '0326'
            section_name: '18. 자본금 (연결)'
          - section_code: '0327'
            section_name: '19. 연결이익잉여금 (연결)'
          - section_code: '0328'
            section_name: '20. 기타자본항목 (연결)'
          - section_code: '0329'
            section_name: '21. 비용의 성격별 분류 (연결)'
          - section_code: '0330'
            section_name: '22. 판매비와관리비 (연결)'
          - section_code: '0331'
            section_name: '23. 기타수익 및 기타비용 (연결)'
          - section_code: '0332'
            section_name: '24. 금융수익 및 금융비용 (연결)'
          - section_code: '0333'
            section_name: '25. 법인세비용 (연결)'
          - section_code: '0334'
            section_name: '26. 주당이익 (연결)'
          - section_code: '0335'
            section_name: '27. 현금흐름표 (연결)'
          - section_code: '0336'
            section_name: '28. 재무위험관리 (연결)'
          - section_code: '0337'
            section_name: '29. 부문별 보고 (연결)'
          - section_code: '0338'
            section_name: '30. 특수관계자와의 거래 (연결)'
          - section_code: '0339'
            section_name: '31. 비지배지분 (연결)'
          - section_code: '0340'
            section_name: '32. 매각예정분류(처분자산집단) (연결)'
          - section_code: '0341'
            section_name: '33. 보고기간 후 사건 (연결)'
      - section_code: '0342'
        section_name: '4. 재무제표'
        children:
          - section_code: '0343'
            section_name: '4-1. 재무상태표'
          - section_code: '0344'
            section_name: '4-2. 손익계산서'
          - section_code: '0345'
            section_name: '4-3. 포괄손익계산서'
          - section_code: '0346'
            section_name: '4-4. 자본변동표'
          - section_code: '0347'
            section_name: '4-5. 현금흐름표'
      - section_code: '0348'
        section_name: '5. 재무제표 주석'
        children:
          - section_code: '0349'
            section_name: '1. 일반적 사항'
          - section_code: '0350'
            section_name: '2. 중요한 회계처리방침'
          - section_code: '0351'
            section_name: '3. 중요한 회계추정 및 가정'
          - section_code: '0352'
            section_name: '4. 범주별 금융상품'
          - section_code: '0353'
            section_name: '5. 금융자산의 양도'
          - section_code: '0354'
            section_name: '6. 공정가치금융자산'
          - section_code: '0355'
            section_name: '7. 매출채권 및 미수금'
          - section_code: '0356'
            section_name: '8. 재고자산'
          - section_code: '0357'
            section_name: '9. 종속기업, 관계기업 및 공동기업 투자'
          - section_code: '0358'
            section_name: '10. 유형자산'
          - section_code: '0359'
            section_name: '11. 무형자산'
          - section_code: '0360'
            section_name: '12. 차입금'
          - section_code: '0361'
            section_name: '13. 사채'
          - section_code: '0362'
            section_name: '14. 순확정급여부채(자산)'
          - section_code: '0363'
            section_name: '15. 충당부채'
          - section_code: '0364'
            section_name: '16. 우발부채와 약정사항'
          - section_code: '0365'
            section_name: '17. 계약부채'
          - section_code: '0366'
            section_name: '18. 자본금'
          - section_code: '0367'
            section_name: '19. 이익잉여금'
          - section_code: '0368'
            section_name: '20. 기타자본항목'
          - section_code: '0369'
            section_name: '21. 비용의 성격별 분류'
          - section_code: '0370'
            section_name: '22. 판매비와관리비'
          - section_code: '0371'
            section_name: '23. 기타수익 및 기타비용'
          - section_code: '0372'
            section_name: '24. 금융수익 및 금융비용'
          - section_code: '0373'
            section_name: '25. 법인세비용'
          - section_code: '0374'
            section_name: '26. 주당이익'
          - section_code: '0375'
            section_name: '27. 현금흐름표'
          - section_code: '0376'
            section_name: '28. 재무위험관리'
          - section_code: '0377'
            section_name: '29. 부문별 보고'
          - section_code: '0378'
            section_name: '30. 특수관계자와의 거래'
          - section_code: '0379'
            section_name: '31. 보고기간 후 사건'
      - section_code: '0380'
        section_name: '6. 배당에 관한 사항'
      - section_code: '0381'
        section_name: '7. 증권의 발행을 통한 자금조달에 관한 사항'
        children:
          - section_code: '0382'
            section_name: '7-1. 증권의 발행을 통한 자금조달 실적'
          - section_code: '0383'
            section_name: '7-2. 증권의 발행을 통해 조달된 자금의 사용실적'
      - section_code: '0384'
        section_name: '8. 기타 재무에 관한 사항'
  - section_code: '0400'
    section_name: 'IV. 이사의 경영진단 및 분석의견'
  - section_code: '0500'
    section_name: 'V. 회계감사인의 감사의견 등'
    children:
      - section_code: '0501'
        section_name: '1. 외부감사에 관한 사항'
      - section_code: '0502'
        section_name: '2. 내부통제에 관한 사항'
  - section_code: '0600'
    section_name: 'VI. 이사회 등 회사의 기관에 관한 사항'
    children:
      - section_code: '0601'
        section_name: '1. 이사회에 관한 사항'
      - section_code: '0602'
        section_name: '2. 감사제도에 관한 사항'
      - section_code: '0603'
        section_name: '3. 주주총회 등에 관한 사항'
  - section_code: '0700'
    section_name: 'VII. 주주에 관한 사항'
  - section_code: '0800'
    section_name: 'VIII. 임원 및 직원 등에 관한 사항'
    children:
      - section_code: '0801'
        section_name: '1. 임원 및 직원 등의 현황'
      - section_code: '0802'
        section_name: '2. 임원의 보수 등'
  - section_code: '0900'
    section_name: 'IX. 계열회사 등에 관한 사항'
  - section_code: '1000'
    section_name: 'X. 대주주 등과의 거래내용'
  - section_code: '1100'
    section_name: 'XI. 그 밖에 투자자 보호를 위하여 필요한 사항'
    children:
      - section_code: '1101'
        section_name: '1. 공시내용 진행 및 변경사항'
      - section_code: '1102'
        section_name: '2. 우발부채 등에 관한 사항'
      - section_code: '1103'
        section_name: '3. 제재 등과 관련된 사항'
      - section_code: '1104'
        section_name: '4. 작성기준일 이후 발생한 주요사항 등 기타사항'
  - section_code: '1200'
    section_name: 'XII. 상세표'
    children:
      - section_code: '1201'
        section_name: '1. 연결대상 종속회사 현황(상세)'
      - section_code: '1202'
        section_name: '2. 계열회사 현황(상세)'
      - section_code: '1203'
        section_name: '3. 타법인출자 현황(상세)'
      - section_code: '1204'
        section_name: '4. 연구개발실적(상세)'